import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: 'chapters',
    },
    {
      type: 'autogenerated',
      dirName: 'glossary',
    },
  ],
};

export default sidebars;
