openapi: 3.0.0

info:
  title: Chapter Context Awareness API
  description: "Extended RAG Chat API with chapter-based search filtering and prioritization"
  version: "1.0.0"

paths:
  /api/v1/chat/ask:
    post:
      summary: Ask a question with optional chapter context
      description: |
        Submit a question to the RAG chatbot with optional chapter context.
        When chapter_context is provided, Qdrant search results are prioritized
        to show results from the current chapter first.
      operationId: askQuestion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
            example:
              question: "What is forward kinematics?"
              chapter_context:
                chapter_id: "ch03"
                chapter_title: "Kinematics"

      responses:
        200:
          description: "Question answered successfully with sources and confidence"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
              example:
                answer: "Forward kinematics is the process of calculating..."
                sources:
                  - chapter_id: "ch03"
                    chapter_title: "Kinematics"
                    section_number: 1
                    section_title: "Forward Kinematics"
                    excerpt: "Forward kinematics involves..."
                    relevance_score: 0.92
                confidence: 0.92
                metadata:
                  confidence_score: 0.92
                  search_latency_ms: 150
                  generation_latency_ms: 1200
                  total_latency_ms: 1450
                  chapter_filtered: true
                  chapter_id: "ch03"

        400:
          description: "Invalid request (missing required fields, format error)"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

        422:
          description: "Unprocessable entity (validation error)"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

        500:
          description: "Server error (RAG pipeline failure, LLM error, Qdrant error)"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ChatRequest:
      type: object
      required:
        - question
      properties:
        question:
          type: string
          minLength: 1
          maxLength: 2000
          description: "User's question (1-2000 characters)"
          example: "What is forward kinematics?"

        selectedText:
          type: string
          nullable: true
          maxLength: 500
          description: "Optional selected text context from page (max 500 chars)"
          example: "Forward kinematics is the process of calculating..."

        pageContext:
          $ref: '#/components/schemas/PageContext'
          nullable: true
          description: "Optional page context where question was asked"

        chapter_context:
          $ref: '#/components/schemas/ChapterContext'
          nullable: true
          description: "NEW: Optional chapter context for filtering search results"

        sessionId:
          type: string
          nullable: true
          description: "Optional session ID for conversation tracking"
          example: "session-abc123"

    ChapterContext:
      type: object
      required:
        - chapter_id
        - chapter_title
      properties:
        chapter_id:
          type: string
          minLength: 1
          maxLength: 100
          pattern: "^[a-z0-9\\-]+$"
          description: "Chapter identifier (alphanumeric and hyphens only)"
          example: "ch03"

        chapter_title:
          type: string
          minLength: 1
          maxLength: 100
          description: "Chapter title"
          example: "Kinematics"

    PageContext:
      type: object
      required:
        - url
        - pathname
        - confidence
      properties:
        url:
          type: string
          format: uri
          description: "Full page URL including protocol and host"
          example: "https://example.com/docs/chapter-3-kinematics"

        pathname:
          type: string
          description: "URL pathname without domain"
          example: "/docs/chapter-3-kinematics"

        chapter:
          type: string
          nullable: true
          description: "Optional extracted chapter name"
          example: "Kinematics"

        section:
          type: string
          nullable: true
          description: "Optional extracted section name"
          example: "Forward Kinematics"

        confidence:
          type: string
          enum: ["high", "medium", "low"]
          description: "Confidence in page context extraction"
          example: "high"

    ChatResponse:
      type: object
      required:
        - answer
        - sources
        - confidence
        - metadata
      properties:
        answer:
          type: string
          description: "LLM-generated answer with optional citations"
          example: "Forward kinematics is the process of calculating the position and orientation of the end-effector based on the joint angles..."

        sources:
          type: array
          items:
            $ref: '#/components/schemas/Source'
          minItems: 1
          description: "Retrieved source chunks with metadata"

        confidence:
          type: number
          minimum: 0
          maximum: 1
          description: "Confidence score for the answer (0-1, higher is more confident)"
          example: 0.92

        metadata:
          $ref: '#/components/schemas/ResponseMetadata'
          description: "Operational metrics for the response"

        error:
          $ref: '#/components/schemas/ErrorInfo'
          nullable: true
          description: "Error information (only if request failed)"

    Source:
      type: object
      required:
        - chapter_id
        - chapter_title
        - section_number
        - section_title
        - excerpt
        - relevance_score
      properties:
        chapter_id:
          type: string
          description: "Chapter identifier (e.g., 'ch03')"
          example: "ch03"

        chapter_title:
          type: string
          description: "Chapter title (e.g., 'Kinematics')"
          example: "Kinematics"

        section_number:
          type: integer
          minimum: 0
          description: "Section number within chapter"
          example: 1

        section_title:
          type: string
          description: "Section title (e.g., 'Forward Kinematics')"
          example: "Forward Kinematics"

        excerpt:
          type: string
          maxLength: 500
          description: "Relevant excerpt from the section (max 500 chars)"
          example: "Forward kinematics involves..."

        relevance_score:
          type: number
          minimum: 0
          maximum: 1
          description: "Cosine similarity score (0-1, higher = more relevant)"
          example: 0.92

        id:
          type: string
          nullable: true
          description: "Optional unique ID for tracking"
          example: "chunk-abc123"

        url:
          type: string
          nullable: true
          format: uri
          description: "Optional URL to source document"
          example: "https://example.com/docs/chapter-3"

    ResponseMetadata:
      type: object
      required:
        - confidence_score
        - search_latency_ms
        - generation_latency_ms
        - total_latency_ms
      properties:
        confidence_score:
          type: number
          minimum: 0
          maximum: 1
          description: "Confidence score based on relevance and citation validity"
          example: 0.92

        search_latency_ms:
          type: integer
          minimum: 0
          description: "Time spent on vector search in milliseconds"
          example: 150

        generation_latency_ms:
          type: integer
          minimum: 0
          description: "Time spent on LLM generation in milliseconds"
          example: 1200

        total_latency_ms:
          type: integer
          minimum: 0
          description: "Total end-to-end latency in milliseconds"
          example: 1450

        selected_text_boosted:
          type: boolean
          nullable: true
          description: "Whether search results were boosted using selected text"
          example: false

        boost_factor:
          type: number
          nullable: true
          minimum: 1.0
          maximum: 5.0
          description: "Boost factor applied to search results (1.0 = no boost)"
          example: 1.0

        selected_text_terms:
          type: array
          items:
            type: string
          nullable: true
          description: "Key terms extracted from selected text"
          example: ["forward", "kinematics"]

        chapter_filtered:
          type: boolean
          nullable: true
          description: "NEW: Whether search results were filtered by chapter"
          example: true

        chapter_id:
          type: string
          nullable: true
          description: "NEW: Which chapter was used for filtering"
          example: "ch03"

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          $ref: '#/components/schemas/ErrorInfo'

    ErrorInfo:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: "Machine-readable error code"
          enum:
            - "INVALID_REQUEST"
            - "VALIDATION_ERROR"
            - "QDRANT_ERROR"
            - "LLM_ERROR"
            - "RATE_LIMITED"
            - "SERVER_ERROR"
          example: "VALIDATION_ERROR"

        message:
          type: string
          description: "Human-readable error message"
          example: "Invalid question format. Maximum 2000 characters allowed."

        details:
          type: object
          nullable: true
          description: "Optional additional error context"
          example:
            field: "question"
            reason: "exceeds_max_length"

servers:
  - url: "http://localhost:8000"
    description: "Development server"

  - url: "https://api.example.com"
    description: "Production server"

tags:
  - name: "Chat"
    description: "RAG chatbot queries with chapter context support"

security: []

x-custom-extensions:
  chapter-filtering:
    enabled: true
    description: "Chapter context filtering is supported"
    deprecation_date: null

  version-history:
    - version: "1.0.0"
      date: "2025-12-06"
      changes:
        - "Added chapter_context request field"
        - "Added chapter_filtered and chapter_id to metadata"
        - "Results re-ranked by chapter when context provided"
